config/routes.rb
Rails.application.routes.draw do
  root 'calendars#new'

  resources :calendars, only: %i[create] do
    get :update_form, on: :collection
  end

  get "*path", to: redirect("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_uni_options, only: %i[new update_form]
  before_action :set_defaults, only: %i[new update_form]

  def new; end

  def update_form
    @uni = params[:uni]
    @year = params[:year]
    @spreadsheet = params[:spreadsheet]
    @pbl = params[:pbl]
    @clin = params[:clin]

    set_instance_vars(@uni, @year, @spreadsheet, @pbl, @clin)

    render turbo_stream: turbo_stream.replace(params[:frame_id], partial: 'calendars/form',
                                                                 locals: { uni: @uni,
                                                                           year: @year,
                                                                           spreadsheet: @spreadsheet,
                                                                           pbl: @pbl,
                                                                           clin: @clin,
                                                                           year_options: @year_options,
                                                                           uni_options: @uni_options,
                                                                           spreadsheet_options: @spreadsheet_options,
                                                                           pbl_options: @pbl_options,
                                                                           clin_options: @clin_options,
                                                                           submit_disabled: @submit_disabled,
                                                                           exclude_pbl_and_clin: @exclude_pbl_and_clin })
  end

  def create
    full_form_file_name = "lib/assets/spreadsheets/#{form_params[:uni].downcase}/#{form_params[:year]}/#{form_params[:spreadsheet]}"

    xlsx = Roo::Excelx.new(full_form_file_name)

    calendar = Calendars::CreateCalendarService.call(
      pbl: form_params[:pbl],
      clin: form_params[:clin],
      year: form_params[:year].to_i,
      uni: form_params[:uni].downcase,
      spreadsheet: xlsx
    )

    calendar = calendar.to_ical

    calendar_name = "timetable_#{Time.zone.now.strftime('%Y%m%d%H%M%S')}.ics"

    Calendar.create(raw: calendar, pbl: form_params[:pbl].downcase, clin: form_params[:clin], year: form_params[:year],
                    uni: form_params[:uni].downcase, spreadsheet: form_params[:spreadsheet])

    send_data calendar, type: 'text/calendar', filename: calendar_name
  rescue StandardError => e
    Sentry.capture_exception(e)
    flash[:alert] = 'Something went wrong'
    redirect_to :root and return
  end

  private

  def form_params
    params.require(:user_input).permit(:clin, :pbl, :spreadsheet, :year, :uni, :complete, :exclude_pbl_and_clin)
  end

  def set_instance_vars(uni, year, spreadsheet, _pbl, _clin)
    if uni == 'UON'
      @year_options = [1, 2]
    elsif uni == 'UNE'
      @year_options = [1]
    end

    @spreadsheet_options = get_spreadsheet_options_for(uni, year) if uni && year

    if spreadsheet
      if uni == 'UNE'
        @pbl_options = ('A'..'H').to_a
        @clin_options = ('1'..'16').to_a
      elsif uni == 'UON'
        @pbl_options = ('A'..'Q').to_a
        @clin_options = ('1'..'20').to_a if year == '1'
      end
    end

    @submit_disabled = !uni || !year || !spreadsheet
  end

  def get_spreadsheet_options_for(uni = '*', year = '*')
    Dir.glob("lib/assets/spreadsheets/#{uni.downcase}/#{year}/*").map do |f|
      f.split('/').last
    end
  end

  def set_uni_options
    @uni_options = %w[UON UNE]
  end

  def set_defaults
    @uni ||= nil
    @year ||= nil
    @spreadsheet ||= nil
    @year_options ||= []
    @uni_options ||= []
    @spreadsheet_options ||= []
    @pbl_options ||= []
    @clin_options ||= []
    @submit_disabled ||= true
    @set_defaults ||= nil
  end
end

app/controllers/generator_controller.rb
class GeneratorController < ApplicationController
    def new
    end

    def create
        response = Aws::LambdaClient.call("jmp_calendar", {
            pbl: "K",
            clin: "18",
            key: "MEDI1101A Timetable Weeks 1 to 3 2024 - Callaghan & Central Coast.xlsx"
        })

        calendar = Icalendar::Calendar.parse(response.payload).first.to_ical

        send_data ics_file, filename: 'event.ics', type: 'text/calendar', disposition: 'attachment'
    end

    private

    def form_params
        params.require(:form).permit(:clin, :pbl)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calendars/_form.erb
<%= form_with scope: :user_input, url: calendars_path, method: :post, local: true, data: { turbo: false }, class: "space-y-4 md:space-y-6" do |form| %>
<%= turbo_frame_tag 'form_frame' do %>
    <div class="w-2/3 m-auto">
        <%= render partial: "select_option", locals: { name: 'uni', label: 'University', value: uni, default: 'Select a Uni', options: uni_options, form: form } %>
        <% if year_options&.any? %>
            <%= render partial: "select_option", locals: { name: 'year', label: 'JMP Year', value: year, default: 'Select JMP Year', options: year_options, form: form } %>

            <% if spreadsheet_options&.any? %>
                <%= render partial: "select_option", locals: { name: 'spreadsheet', label: 'Timetable spreadsheet', value: spreadsheet, default: 'Select a timetable', options: spreadsheet_options, form: form } %>

                <div class="py-2">
                    <%= render partial: "no_clin_pbl_radio_button", locals: { form: form } %>
                </div>

                <% if pbl_options&.any? %>
                    <%= render partial: "select_option", locals: { name: 'pbl', label: 'PBL Group', value: pbl, default: 'Select a PBL', options: pbl_options, form: form } %>
                <% end  %>

                <% if clin_options&.any? %>
                    <%= render partial: "select_option", locals: { name: 'clin', label: 'CLIN SKills Group', value: clin, default: 'Select a CLIN', options: clin_options, form: form } %>
                <% end  %>
            <% end  %>
        <% end %>

        <%= form.hidden_field :complete, value: submit_disabled %>
        <%= form.hidden_field :uni, value: uni %>
        <%= form.hidden_field :year, value: year %>
        <%= form.hidden_field :spreadsheet, value: spreadsheet %>
        <%= form.hidden_field :pbl, value: pbl %>
        <%= form.hidden_field :clin, value: clin %>
        <%= form.hidden_field :exclude_pbl_and_clin, value: exclude_pbl_and_clin %>

        <div class="flex justify-center">
            <%= form.submit "Submit",
                disabled: submit_disabled,
                class: "mt-3 w-full md:w-auto px-6 py-2 border border-transparent shadow-sm text-base md:text-md font-medium rounded-md text-white " +
                        "#{submit_disabled ? 'bg-gray-500 hover:bg-gray-500' : 'bg-blue-500 hover:bg-blue-600'} focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>

        </div>
    </div>
    <% end %>
<% end %>

app/views/calendars/_no_clin_pbl_radio_button.html.erb
<%= form.label :exclude_pbl_and_clin, "Exclude PBL and CLIN classes? (for Staff)", class: "block text-md md:text-lg font-medium text-gray-800" %>
<%= form.radio_button :exclude_pbl_and_clin, false %>

app/views/calendars/_select_option.html.erb
<%= form.label name, label, class: "block text-md md:text-lg font-medium text-gray-800" %>
<%= form.select name,
    options_for_select(options, selected: value.present? ? value : nil),
    { include_blank: value.present? ? false : default },
    data: {
        controller: "form-updates",
        action: "change->form-updates#updateForm",
        frame_id: "form_frame"
    },
    id: "#{name}_select",
    class: "mt-1 block w-full py-2 px-3 border border-gray-200 bg-white rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 text-base md:text-md",
    disabled: value.present?
%>

app/views/calendars/new.html.erb
<div class="flex justify-center w-screen pt-12 m-auto">
  <div class="mx-4 m-auto bg-gray-50 shadow-lg rounded-lg p-6 md:p-8">
    <h2 class="text-center text-3xl md:text-4xl font-bold text-gray-800 mb-6 md:mb-8">Get Your JMP Timetable</h2>
    <p class="text-gray-600">Generate an <strong>ics</strong> file which can be imported into any calendar app (<a href="https://support.google.com/calendar/answer/37118?hl=en&co=GENIE.Platform%3DDesktop" class="ml-auto text-blue-500 hover:text-blue-600 underline">Gmail</a>, <a href="https://support.microsoft.com/en-au/office/import-or-subscribe-to-a-calendar-in-outlook-com-or-outlook-on-the-web-cff1429c-5af6-41ec-a5b4-74f2c278e98c#:~:text=Select%20Upload%20from%20file.,to%2C%20and%20then%20select%20Import." class="ml-auto text-blue-500 hover:text-blue-600 underline">Outlook</a>, <a href="https://support.apple.com/en-vn/guide/iphone/iph3d1110d4/ios#:~:text=Create%20an%20iCloud%20calendar%3A%20Tap,information)%2C%20then%20click%20Subscribe." class="ml-auto text-blue-500 hover:text-blue-600 underline">Apple</a> etc).
    <br/>
    <p class="text-gray-600">This will be updated as future timetable versions are released.</p>
    <% if flash[:alert] %>
      <div class="text-red-600">
      <br/>
      <p class="text-red-600"><%= flash[:alert] %></p>
      </div>
    <% end %>
    <div class="flex items-center mt-4x">
      <%= link_to "clear choices", root_path, class: "ml-auto text-red-600 hover:text-red-600 right" %>
    </div>
    <%= render partial: 'form', locals: { uni: @uni,
                year: @year,
                spreadsheet: @spreadsheet,
                pbl: @pbl,
                clin: @clin,
                year_options: @year_options,
                uni_options: @uni_options,
                spreadsheet_options: @spreadsheet_options,
                pbl_options: @pbl_options,
                clin_options: @clin_options,
                submit_disabled: @submit_disabled,
                exclude_pbl_and_clin: @exclude_pbl_and_clin
              } %>

    <div class="flex items-center">
      <a href="mailto:c3438165@uon.edu.au?subject=I need help with my timetable" class="ml-auto text-blue-500 hover:text-blue-600">
        Need help?
      </a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JmpCalendarWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  <script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="badena" data-description="Support me on Buy me a coffee!" data-message="Thanks for visiting 🙏. I'm a poor uni student too 😄 Buy me a coffee?" data-color="#5F7FFF" data-position="Right" data-x_margin="18" data-y_margin="18"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>